#include "Biome.h"
#include "Engine/World.h"
#include "DrawDebugHelpers.h" // Optional: For debugging raycasts
#include "CharmingCraft/Core/Builds/Lib/BuildModuleLib.h"
#include "CharmingCraft/Core/Bus/GameEventHandler.h"
#include "CharmingCraft/Core/Log/Logging.h"
#include "CharmingCraft/Object/Class/Core/CharmingCraftInstance.h"
#include "Components/BoxComponent.h"


ABiome::ABiome()
{
	PrimaryActorTick.bCanEverTick = true;
	BiomeBound = CreateDefaultSubobject<UBoxComponent>("Biome Bound");
	BiomeBound->SetupAttachment(RootComponent);
}

void ABiome::BeginPlay()
{
	Super::BeginPlay();
	GameEventHandler = Cast<UCharmingCraftInstance>(GetGameInstance())->GamePlayLogicManager;
	GameEventHandler->OnResourceEntityBreak.AddDynamic(this, &ABiome::OnResourceEntityBreakEvent);

	// Init Biome with some preload resource actor
	InitBiomeActor();

	// Register Timer, keep generate resource
	StartBiomeDataTimer();
}

bool ABiome::GetRandomPointInVolume(FVector& OutLocation)
{
	FVector Origin;
	FVector BoxExtent;
	GetActorBounds(false, Origin, BoxExtent);

	FVector RandPoint = UBuildModuleLib::SnapToGrid(Origin + FMath::RandPointInBox(FBox(-BoxExtent, BoxExtent)), 100);;


	// å°„çº¿æŠ•å°„ä»¥æ£€æŸ¥åœ°é¢
	FHitResult HitResult;
	FCollisionQueryParams CollisionParams;
	CollisionParams.AddIgnoredActor(this); // å¿½ç•¥è‡ªèº«
	bool bHit = GetWorld()->LineTraceSingleByChannel(HitResult, RandPoint, RandPoint - FVector(0, 0, 10000),
	                                                 ECC_WorldStatic, CollisionParams);

	if (bHit)
	{
		// æ£€æŸ¥åˆ°åœ°é¢ï¼Œè¿”å›åœ°é¢ä¸Šæ–¹çš„ä½ç½®
		OutLocation = HitResult.Location;
		return true;
	}

	// æ²¡æœ‰æ£€æŸ¥åˆ°åœ°é¢ï¼Œè¿”å›å¤±è´¥
	return false;
}

void ABiome::OnResourceEntityBreakEvent(AActor* Breaker, AResourceEntityActor* TargetResourceEntity)
{
	UE_LOG(LogChamingCraftResource, Display,
	       TEXT("[ğŸª¨ï¸]  Biome Internal resource actor update\n"
		       "		 [B] Biome =		%s\n"
		       "		 [R] Resource =		%s\n"
		       "		 [I] Instigator =	%s"), *BiomeRegisterName.ToString(),
	       *TargetResourceEntity->ResourceName.ToString(), *Breaker->GetName());
	ResourceEntityActorPool.Remove(TargetResourceEntity);
}

float ABiome::GetOnGenerateSuccessRate(FBiomeData BiomeData)
{
	int32 BiomeIncludeResource = 0;
	for (auto ResourceEntity : ResourceEntityActorPool)
	{
		if (ResourceEntity.GetClass() == BiomeData.ResourceEntityActorClass.Get())
		{
			BiomeIncludeResource++;
		}
	}
	return 1 - (BiomeIncludeResource / BiomeData.MaxPerBiome);
}

bool ABiome::StartBiomeDataTimer()
{
	for (auto &BiomeData : RegisterBiomeData)
	{

		GetWorld()->GetTimerManager().SetTimer(BiomeData.ResourceInternalTimer, [this, BiomeData]()
		                                       {
			                                       this->GenerateResource(BiomeData);
		                                       },
		                                       BiomeData.RegenerateTick, true);
	}
	return true;
}

void ABiome::GenerateResource(FBiomeData BiomeData)
{
	// è·å–ç”ŸæˆæˆåŠŸçš„æ¦‚ç‡
	float SuccessRate = GetOnGenerateSuccessRate(BiomeData);

	// ç”Ÿæˆä¸€ä¸ª0åˆ°1ä¹‹é—´çš„éšæœºæ•°
	float RandomChance = FMath::FRand();

	// å¦‚æœéšæœºæ•°å°äºç­‰äºç”Ÿæˆå‡ ç‡ï¼Œåˆ™ç”ŸæˆActor
	if (RandomChance <= SuccessRate)
	{
		if (!this)
		{
			return;
		}
		FVector SpawnLocation;
		if (GetRandomPointInVolume(SpawnLocation))
		{
			// å°è¯•åœ¨è®¡ç®—å‡ºçš„ä½ç½®ç”Ÿæˆèµ„æºå®ä½“
			AResourceEntityActor* SpawnedActor = GetWorld()->SpawnActor<AResourceEntityActor>(
				BiomeData.ResourceEntityActorClass, SpawnLocation, FRotator::ZeroRotator);
			if (SpawnedActor)
			{
				ResourceEntityActorPool.Add(SpawnedActor);
			}
		}
	}
}

void ABiome::InitBiomeActor()
{
	// éå†æ³¨å†Œçš„BiomeDataï¼Œç”Ÿæˆèµ„æºå®ä½“
	for (const FBiomeData& BiomeData : RegisterBiomeData)
	{
		// ç¡®å®šç”Ÿæˆæ•°é‡
		int32 NumToSpawn = FMath::RandRange(BiomeData.MinPerBiome, BiomeData.MaxPerBiome);

		for (int32 i = 0; i < NumToSpawn; ++i)
		{
			FVector SpawnLocation;
			if (GetRandomPointInVolume(SpawnLocation))
			{
				// å°è¯•åœ¨è®¡ç®—å‡ºçš„ä½ç½®ç”Ÿæˆèµ„æºå®ä½“
				AResourceEntityActor* SpawnedActor = GetWorld()->SpawnActor<AResourceEntityActor>(
					BiomeData.ResourceEntityActorClass, SpawnLocation, FRotator::ZeroRotator);
				if (SpawnedActor)
				{
					ResourceEntityActorPool.Add(SpawnedActor);
				}
			}
		}
	}
}


void ABiome::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}
